### ISSUE TITLE
Component does not seem to work

### ISSUE THREAD

**Issue by sdrasmussen** [Danielhiversen/pySwitchmate#1]
Hi, Daniel.  I have about 9 Switchmate products, so I was extremely pleased to see support added for them in Home Assistant.  I installed the latest beta release this morning, and then attempted to configure the Switchmate platform for two of my devices.  I don't think it is working, because I get the following in the logs:

2018-09-12 12:51:27 ERROR (SyncWorker_14) [homeassistant.components.switch.switchmate] Failed to set up switchmate
2018-09-12 12:51:27 WARNING (MainThread) [homeassistant.components.switch] Platform switchmate not ready yet. Retrying in 180 seconds.

Did I do something wrong?

**Comment by Danielhiversen** [comment]
Try to use the latest dev version of Home assistant. I think you are using the first version of the component.

Are you sure the mac address is correct?
Do you use the latest firmware for your switches?

Enable logging for the pySwitchmate library: 


```
logger:
  default: warning
  logs:
     pySwitchmate: debug

```

I just added some more debugging, so you should also try to use the latest version of the library.
I would need more info to figure out what is wrong here.

**Comment by sdrasmussen** [comment]
Daniel, I am running version 0.78.0b2 of Home Assistant.  I am sure the MAC address is correct.  It is for a "Switchmate Power".  I always have the latest firmware on my Switchmates.  I turned on debug.  This is what I get:

2018-09-13 13:19:42 WARNING (MainThread) [homeassistant.components.switch] Setup of platform switchmate is taking over 10 seconds.
2018-09-13 13:20:13 ERROR (SyncWorker_10) [homeassistant.components.switch.switchmate] Failed to set up switchmate
2018-09-13 13:20:13 WARNING (MainThread) [homeassistant.components.switch] Platform switchmate not ready yet. Retrying in 60 seconds.
2018-09-13 13:21:24 WARNING (MainThread) [homeassistant.components.switch] Setup of platform switchmate is taking over 10 seconds.
2018-09-13 13:21:55 ERROR (SyncWorker_5) [homeassistant.components.switch.switchmate] Failed to set up switchmate
2018-09-13 13:21:55 WARNING (MainThread) [homeassistant.components.switch] Platform switchmate not ready yet. Retrying in 90 seconds.
2018-09-13 13:23:36 WARNING (MainThread) [homeassistant.components.switch] Setup of platform switchmate is taking over 10 seconds.
2018-09-13 13:24:06 ERROR (SyncWorker_6) [homeassistant.components.switch.switchmate] Failed to set up switchmate
2018-09-13 13:24:06 WARNING (MainThread) [homeassistant.components.switch] Platform switchmate not ready yet. Retrying in 120 seconds.

**Comment by Danielhiversen** [comment]
Is that a wifi device?
This is only for the bluetooth devices.

**Comment by sdrasmussen** [comment]
Is it a wifi device.  I can try to configure a bluetooth device.  Full
disclosure....I am running home assistant on Ubuntu on a laptop.  Will that
be expected to work?

**Comment by Danielhiversen** [comment]
That should work if you have bluetooth on your laptop

**Comment by sdrasmussen** [comment]
Well, the setup succeeded this time.  I'll have to wait until I get home to tell if it actually works or not and will record my results here tonight (I am in the US). .

**Comment by sdrasmussen** [comment]
Ok.  I'm home.  I have two switchmates configured.  One is bluetooth only,
and the other is a Power, which does wifi and bluetooth; I have the
bluetooth interface configured.  The bluetooth only works, BUT it is in an
opposite state from reality, i.e. Home Assistant thinks it is on when it is
off, and off when it is on.  The Power, when I try to toggle it, indicates
on, then bounces back to off, and nothing actually happens with it.
Thoughts?

**Comment by Danielhiversen** [comment]
That should be fixed in this library now.
I will push an update to HA after some more testing

**Comment by Danielhiversen** [comment]
The fix is now merged to the dev branch of HA

**Comment by sdrasmussen** [comment]
I think there may be a bit of a development problem with this platform that you may not be aware of. In my environment, I have a Switchmate Power (which is a two switch Wifi and Bluetooth device) and 7 regular Switchmates (Bluetooth only).  The Switchmate power acts as a hub for the bluetooth only devices, and that is what allows the other Switchmates to talk to Alexa or Google Home, and to be accessible from off of the local network.  With your component, I have observed some improper behavior. I have so far configured four of my Switchmates in Home Assistant.  Those same four will now not associate with the Switchmate Power, effectively breaking the manufacturer's intended functioning.  Also, Alexa can no longer control those four.  If I can be of any assistance in providing testing, I'd be glad to. I am not a programmer, but do have in my possession the aforementioned gear.

**Comment by Danielhiversen** [comment]
Are you using the dev branch of HA (the latest version of this library)?

I guess that only one hub can be connected to a switch at the same time.
So when HA connects, the device get disconnected from the other hub. 
And if the hub does not reconnect to the switch, it will stay offline.
I am not sure if this can be fixed by this library.
So you probably have to choose where you want to control your switches.

**Comment by sdrasmussen** [comment]
Daniel, I am not really sure when you use the term "library".  All I can
tell you about my HA installation is that I am subscribed to the Beta
channel, and therefore will be running the latest Beta of HA, but as it
stands at this moment, that happens to be the same version as general
release which is 0.78.1.  So, I do not know if there is another "version"
of the Switchmate component I could be running, as I do not know how to do
that.

I am curious about how you went about developing this component, i.e. were
you in communication with Switchmate developers? Or was this developed by
reverse engineering?  Because I do understand that we are probably hitting
a limit of how bluetooth pairing can work in this scenario.  I am wondering
if the approach could be to have HA control Switchmates through their
cloud, or whatever they have to circumvent this problem, just like say what
HA does with Ring doorbell, or August locks, or Wemos.  Just throwing that
out there, because by using this component, if that breaks Alexa
connectivity (which it does), it won't be an option for users like me.
Thanks for your work.
