### ISSUE TITLE
Dependency fails on MacOS

### ISSUE THREAD

**Issue by thevickypedia** [Danielhiversen/pySwitchmate#10]
Unable to install the dependency `bluepy`

```
fatal error: 'byteswap.h' file not found
#include` <byteswap.h>
1 error generated.
make: *** [bluepy-helper] Error 1"
  ----------------------------------------
  ERROR: Failed building wheel for bluepy
```

I've also raised an [issue](https://github.com/IanHarvey/bluepy/issues/194#issuecomment-733696079) with `bluepy` but is there any way around to get `pySwitchmate` working on my Mac?

**Comment by Danielhiversen** [comment]
It requires bluepy
